// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	models "computer-club/internal/repository/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "computer-club/internal/repository"
)

// ComputerRepository is an autogenerated mock type for the ComputerRepository type
type ComputerRepository struct {
	mock.Mock
}

// GetComputers provides a mock function with given fields: ctx
func (_m *ComputerRepository) GetComputers(ctx context.Context) ([]models.Computer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetComputers")
	}

	var r0 []models.Computer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Computer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Computer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Computer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsComputerAvailable provides a mock function with given fields: ctx, tx, number
func (_m *ComputerRepository) IsComputerAvailable(ctx context.Context, tx repository.Transaction, number int) (bool, error) {
	ret := _m.Called(ctx, tx, number)

	if len(ret) == 0 {
		panic("no return value specified for IsComputerAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int) (bool, error)); ok {
		return rf(ctx, tx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int) bool); ok {
		r0 = rf(ctx, tx, number)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int) error); ok {
		r1 = rf(ctx, tx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkComputerFree provides a mock function with given fields: ctx, tx, number
func (_m *ComputerRepository) MarkComputerFree(ctx context.Context, tx repository.Transaction, number int) error {
	ret := _m.Called(ctx, tx, number)

	if len(ret) == 0 {
		panic("no return value specified for MarkComputerFree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int) error); ok {
		r0 = rf(ctx, tx, number)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewComputerRepository creates a new instance of ComputerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComputerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComputerRepository {
	mock := &ComputerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
