package errors

import "errors"

var (
	ErrUserNotFound       = errors.New("пользователь не найден")
	ErrJSONRequest        = errors.New("ошибка JSON запроса")
	ErrInvalidRole        = errors.New("некорректная роль")
	ErrUserAlreadyExists  = errors.New("пользователь уже существует")
	ErrInvalidCredentials = errors.New("неверный email или пароль")
	ErrUsernameTaken      = errors.New("пользователь с таким никнеймом уже существует")
	ErrHashedPassword     = errors.New("проблема с хешированием пароля")
	ErrPasswordTooShort   = errors.New("пароль должен содержать минимум 6 символов")
	ErrCreatedUser        = errors.New("ошибка при создании в базу данных пользователя")
	ErrCreatedSession     = errors.New("ошибка при создании в базу данных сессии")
	ErrUpdateSession      = errors.New("ошибка обновления сессии в базу данных")
	ErrUpdateComputer     = errors.New("ошибка обновления компьютера в базу данных")
	ErrFindComputer       = errors.New("ошибка при поиске компьютера в базе данных")
	ErrFindUser           = errors.New("ошибка при поиске пользователя в базе данных")
	ErrNameEmpty          = errors.New("имя не может быть пустым")
	ErrPasswordEmpty      = errors.New("пароль не может быть пустым")
	ErrEmailEmpty         = errors.New("почта не может быть пустая")
	ErrSessionNotFound    = errors.New("сессия не найдена")
	ErrSessionActive      = errors.New("у пользователя уже есть активная сессия")
	ErrPCBusy             = errors.New("компьютер уже занят")
	ErrInvalidSessionID   = errors.New("некорректный идентификатор сессии")
	ErrRegistration       = errors.New("ошибка при регистрации пользователя")
	ErrComputerNotFound   = errors.New("компьютер не найден")
	ErrTokenGeneration    = errors.New("ошибка генерации токена")
	ErrUnexpected         = errors.New("неизвестная ошибка")
	ErrMissingToken       = errors.New("токен не найден в хедере")
	ErrWrongToken         = errors.New("токен не правильный")
)
