server:
  port: 50051

database:
  host: localhost
  port: 5432
  user: admin
  password: 123456
  dbname: clubdb
  sslmode: disable

jwt:
  secret: "supersecretkey"
  expire_hours: 24

log:
  level: "info"
  file: "logs/app.log"
